import tracemalloc
from Student import Student
tot_iteration = 100
def mem_testing_method():
    for i in range(tot_iteration):
        new_student = Student("Glen", "Business", 3.5, True)
        print(new_student.on_special_degree())
def mem_testing_method2():
    new_student = Student("Glen", "Business", 3.5, True)
    print(new_student.on_special_degree())
    new_student1 = Student("Glen1", "Business", 3.5, True)
    print(new_student1.on_special_degree())
    new_student2= Student("Glen2", "Business", 3.5, True)
    print(new_student2.on_special_degree())
    new_student3 = Student("Glen3", "Business", 3.5, True)
    print(new_student3.on_special_degree())
    new_student4 = Student("Glen4", "Business", 3.5, True)
    print(new_student4.on_special_degree())
    new_student5 = Student("Glen3", "Business", 3.5, True)
    print(new_student5.on_special_degree())
    new_student6 = Student("Glen", "Business", 3.5, True)
    print(new_student6.on_special_degree())
    new_student7 = Student("Glen", "Business", 3.5, True)
    print(new_student7.on_special_degree())
    new_student8 = Student("Glen", "Business", 3.5, True)
    print(new_student8.on_special_degree())
    new_student9 = Student("Glen", "Business", 3.5, True)
    print(new_student9.on_special_degree())
    new_student10 = Student("Glen", "Business", 3.5, True)
    print(new_student10.on_special_degree())
    new_student11 = Student("Glen", "Business", 3.5, True)
    print(new_student11.on_special_degree())
    new_student12 = Student("Glen", "Business", 3.5, True)
    print(new_student12.on_special_degree())
    new_student13 = Student("Glen", "Business", 3.5, True)
    print(new_student13.on_special_degree())
    new_student14 = Student("Glen", "Business", 3.5, True)
    print(new_student14.on_special_degree())

tracemalloc.start()
mem_testing_method()
current, peak = tracemalloc.get_traced_memory()
print(f"Current memory usage is {current / 10**6}MB; Peak was {peak / 10**6}MB")
tracemalloc.stop()

tracemalloc.start()
mem_testing_method2()
current, peak = tracemalloc.get_traced_memory()
print(f"Current memory usage is {current / 10**6}MB; Peak was {peak / 10**6}MB")
tracemalloc.stop()